name: CI/CD Pipeline on Github Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-command-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Run a Sheel Command
        run: echo "Hello, World!"
